# Generated by Django 5.0.4 on 2024-04-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Все новости'},
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='News_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsworld.newscategory')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Все новости',
            },
        ),
    ]
