# Generated by Django 5.0.4 on 2024-05-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsworld', '0004_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='user_news_quantity',
        ),
    ]
